"""Programmable instance generation on a natural complexity grade.

The learned adversarial proposer was measured over 8 seeds and is
indistinguishable from a uniform-random one (+0.15, 95% CI [-0.06, +0.35]),
while collapsing to *worse* than random on some initialisations. By the criterion
in `research/01-game-design.md` -- admit a proposer only if it beats an
independent generator -- it does not earn its place, so this replaces it.

It also matches how the difficulty actually arises. Mathematics does not advance
by constructing problems nobody can solve; it advances outward from what is
already solved, and the objects it works on come with their own canonical
difficulty axis. Here that axis is given, not invented:

    complexity = crossing_weight * c  +  N

with `c` the crossing number of the source knot and `N` the number of scramble
moves applied on top of a canonical braid word for it. Two independent knobs,
both meaningful, neither learned.

The source family is **torus knots**, because they are generated by a formula
rather than transcribed from a table, so there is nothing to get wrong:

    T(p, q) = (sigma_1 sigma_2 ... sigma_{p-1})^q   in B_p

whose closure is a knot exactly when gcd(p, q) = 1, with crossing number
min(p(q-1), q(p-1)) for 2 <= p < q. T(2,3) is the trefoil, T(2,5) is 5_1,
T(3,4) is 8_19. The unknot is the empty word in B_1, so the existing game is the
c = 0 row of the same table.

A note on the objective this implies. Every move in this project preserves the
closure, so any word reachable from a source *is* that knot -- there is no need
to verify the type. "Undo the scramble" is therefore exactly "reach a word no
longer than the canonical one", which reduces to the current win condition
(reach the empty 1-braid) when the source is the unknot.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

Word = tuple[int, ...]


def torus_braid(p: int, q: int) -> tuple[Word, int]:
    """Braid word for the torus knot/link T(p, q) and its strand count.

    `(sigma_1 ... sigma_{p-1})^q` on `p` strands. The closure is a **knot** only
    when `gcd(p, q) = 1`; otherwise it has `gcd(p, q)` components.
    """
    if p < 1 or q < 1:
        raise ValueError("torus parameters must be positive")
    generators = tuple(range(1, p))
    return generators * q, max(p, 1)


def torus_crossing_number(p: int, q: int) -> int:
    """Crossing number of T(p, q) for coprime 2 <= p < q."""
    if p < 2 or q < 2:
        return 0
    return min(p * (q - 1), q * (p - 1))


def torus_unknotting_number(p: int, q: int) -> int:
    """`u(T(p,q)) = (p-1)(q-1)/2` -- the Milnor conjecture, proved by
    Kronheimer and Mrowka (1993).

    This is why torus knots are the right source family. The unknotting number is
    the quantity the whole project is ultimately about, it is *unknown* for many
    knots, and here it is a **theorem** rather than an estimate. An agent
    minimising crossing changes on these instances can be scored against exact
    ground truth instead of against a search that might simply not have looked
    hard enough.
    """
    if p < 2 or q < 2:
        return 0
    if math.gcd(p, q) != 1:
        raise ValueError(f"T({p},{q}) is a link, not a knot")
    return (p - 1) * (q - 1) // 2


@dataclass(frozen=True)
class Source:
    """A canonical starting point: a knot, and one braid word representing it."""

    name: str
    word: Word
    strands: int
    crossing_number: int
    unknotting_number: int = 0

    @property
    def canonical_length(self) -> int:
        return len(self.word)


def torus_sources(max_strands: int, max_crossings: int) -> list[Source]:
    """Every torus knot that fits, ordered by crossing number.

    Deliberately generated rather than tabulated. A transcribed knot table is a
    place to make a silent mistake; a formula is not.
    """
    sources = [Source("unknot", (), 1, 0)]
    seen: set[tuple[int, int]] = set()
    for p in range(2, max_strands + 1):
        for q in range(2, 2 * max_crossings + 2):
            if math.gcd(p, q) != 1:
                continue  # a link, not a knot
            crossings = torus_crossing_number(p, q)
            if crossings > max_crossings or (p, q) in seen:
                continue
            seen.add((p, q))
            word, strands = torus_braid(p, q)
            sources.append(
                Source(
                    f"T({p},{q})",
                    word,
                    strands,
                    crossings,
                    torus_unknotting_number(p, q),
                )
            )
    unique: dict[int, Source] = {}
    for source in sources:
        # One representative per crossing number keeps the grade monotone.
        if source.crossing_number not in unique:
            unique[source.crossing_number] = source
    return sorted(unique.values(), key=lambda s: s.crossing_number)


@dataclass(frozen=True)
class Instance:
    word: Word
    strands: int
    source: str
    crossing_number: int
    scramble_moves: int
    canonical_length: int

    def complexity(self, crossing_weight: int = 5) -> int:
        return crossing_weight * self.crossing_number + self.scramble_moves


class GradedGenerator:
    """Instances on an explicit complexity grade, with no learning anywhere.

    `crossing_weight` sets how much a crossing of the source knot counts against
    a scramble move, so a single integer orders the whole space:

        complexity = crossing_weight * crossing_number + scramble_moves
    """

    def __init__(
        self,
        config,
        *,
        max_crossings: int = 0,
        crossing_weight: int = 5,
    ):
        self.config = config
        self.crossing_weight = crossing_weight
        self.sources = [
            source
            for source in torus_sources(config.max_strands, max_crossings)
            if source.strands <= config.max_strands
            and source.canonical_length + 2 <= config.max_len
        ]

    def levels(self, max_scramble: int) -> list[tuple[Source, int]]:
        """Every (source, scramble count) pair, ordered by complexity."""
        pairs = [
            (source, moves)
            for source in self.sources
            for moves in range(max_scramble + 1)
        ]
        return sorted(
            pairs,
            key=lambda pair: (
                self.crossing_weight * pair[0].crossing_number + pair[1],
                pair[0].crossing_number,
            ),
        )

    def generate(self, source: Source, scramble_moves: int, rng: np.random.Generator) -> Instance:
        """Apply `scramble_moves` uniform-random type-preserving moves.

        Every move preserves the closure, so the result is still `source` -- the
        ground truth is exact and free, exactly as with the unknot-only game.
        """
        from rf_knots.actions import PASS, ActionSpec
        from rf_knots.reference import successors

        spec = ActionSpec(self.config.max_len, self.config.max_strands)
        word, strands = source.word, source.strands
        for _ in range(scramble_moves):
            options = successors(spec, word, strands, allow_crossing=False)
            options = [o for o in options if spec.decode(o[0])[0] != PASS]
            if not options:
                break
            _, word, strands = options[int(rng.integers(len(options)))]
        return Instance(
            word=word,
            strands=strands,
            source=source.name,
            crossing_number=source.crossing_number,
            scramble_moves=scramble_moves,
            canonical_length=source.canonical_length,
        )
